name: Bug Report Formular
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "needs-confirmation"]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: By submitting this bug issue, you agree to the following.
      options:
        - label: This bug does not happen due to changed c++ source code (vanilla version)
          required: true
        - label: This bug has not been resolved in master branch
          required: true
  - type: dropdown
    id: server-version
    attributes:
      label: Server Version
      description: Which version was this tested on?
      multiple: true
      options:
        - 1.7 (Master)
        - 1.6 (Release)
        - 1.5 (Development)
        - 1.4.x (Release)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operation System
      description: On which OS does this bug appear?
      multiple: true
      options:
        - Windows
        - Ubuntu 20.04
        - Ubuntu 22.04
        - Ubuntu 24.04
        - Debian 12
        - MacOS
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Tell us step by step how to reproduce this bug
      value: 1.. 2.. 3..
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should normaly happen?
      placeholder: Please include video/screenshot (if possible)
      value: "expected behavior"
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: This is what happens instead
      placeholder: Please include video/screenshot (if possible)
      value: "actual behavior"
    validations:
      required: true
  - type: textarea
    id: backtrace
    attributes:
      label: Backtrace
      description: Please provide a backtrace of your debugger if this bug crashes tfs.
      placeholder: This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
