name: Feature Request
description: Requesting a new feature for the engine or data pack
title: "[Feature]: "
labels: ["feature"]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: By submitting this bug issue, you agree to the following.
      options:
        - label: There is no existing issue for this feature (or similar) already
          required: true
  - type: textarea
    id: pr
    attributes:
      label: Pull Requests or Links to add this feature
      description: |
        If there is a PR which adds this functionality, please link it here
        If there is another source which adds this functionality, please link it here
        Delete everything inside if there aren't any
      placeholder: |
        - [x] #pr1
        link to Wiki/Forum/other
      value: |
        - [x] #
        link to Wiki/Forum/other
  - type: textarea
    id: request
    attributes:
      label: Explanation of what you want to do that is currently impossible
      description: Tell us what you tried to do to make it possible and why it didn't work
      value: |
        **What do you want to achieve?**

        **Code if there is any:**
        ```lua
        -- paste your script here
        ```
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Possible Solutions
      description: This is what you think could be a solution to your problem
      placeholder: Please include any code snippets or ideas you have
