// Copyright 2022 The Forgotten Server Authors. All rights reserved.
// Use of this source code is governed by the GPL-2.0 License that can be found in the LICENSE file.

#include "otpch.h"

#include "luaenums.h"

#include "configmanager.h"
#include "const.h"
#include "creature.h"
#include "enums.h"
#include "game.h"
#include "item.h"
#include "luascript.h"
#include "monsters.h"
#include "player.h"

#define registerEnum(i, value) \
	{ \
		std::string enumName = #value; \
		i->registerGlobalVariable(enumName.substr(enumName.find_last_of(':') + 1), value); \
	}

#define registerEnumIn(i, tableName, value) \
	{ \
		std::string enumName = #value; \
		i->registerVariable(tableName, enumName.substr(enumName.find_last_of(':') + 1), value); \
	}

void LuaEnums::registerEnums(LuaScriptInterface* interface)
{
	registerEnum(interface, ACCOUNT_TYPE_NORMAL);
	registerEnum(interface, ACCOUNT_TYPE_TUTOR);
	registerEnum(interface, ACCOUNT_TYPE_SENIORTUTOR);
	registerEnum(interface, ACCOUNT_TYPE_GAMEMASTER);
	registerEnum(interface, ACCOUNT_TYPE_COMMUNITYMANAGER);
	registerEnum(interface, ACCOUNT_TYPE_GOD);

	registerEnum(interface, AMMO_NONE);
	registerEnum(interface, AMMO_BOLT);
	registerEnum(interface, AMMO_ARROW);
	registerEnum(interface, AMMO_SPEAR);
	registerEnum(interface, AMMO_THROWINGSTAR);
	registerEnum(interface, AMMO_THROWINGKNIFE);
	registerEnum(interface, AMMO_STONE);
	registerEnum(interface, AMMO_SNOWBALL);

	registerEnum(interface, BUG_CATEGORY_MAP);
	registerEnum(interface, BUG_CATEGORY_TYPO);
	registerEnum(interface, BUG_CATEGORY_TECHNICAL);
	registerEnum(interface, BUG_CATEGORY_OTHER);

	registerEnum(interface, CALLBACK_PARAM_LEVELMAGICVALUE);
	registerEnum(interface, CALLBACK_PARAM_SKILLVALUE);
	registerEnum(interface, CALLBACK_PARAM_TARGETTILE);
	registerEnum(interface, CALLBACK_PARAM_TARGETCREATURE);

	registerEnum(interface, COMBAT_FORMULA_UNDEFINED);
	registerEnum(interface, COMBAT_FORMULA_LEVELMAGIC);
	registerEnum(interface, COMBAT_FORMULA_SKILL);
	registerEnum(interface, COMBAT_FORMULA_DAMAGE);

	registerEnum(interface, DIRECTION_NORTH);
	registerEnum(interface, DIRECTION_EAST);
	registerEnum(interface, DIRECTION_SOUTH);
	registerEnum(interface, DIRECTION_WEST);
	registerEnum(interface, DIRECTION_SOUTHWEST);
	registerEnum(interface, DIRECTION_SOUTHEAST);
	registerEnum(interface, DIRECTION_NORTHWEST);
	registerEnum(interface, DIRECTION_NORTHEAST);

	registerEnum(interface, COMBAT_NONE);
	registerEnum(interface, COMBAT_PHYSICALDAMAGE);
	registerEnum(interface, COMBAT_ENERGYDAMAGE);
	registerEnum(interface, COMBAT_EARTHDAMAGE);
	registerEnum(interface, COMBAT_FIREDAMAGE);
	registerEnum(interface, COMBAT_UNDEFINEDDAMAGE);
	registerEnum(interface, COMBAT_LIFEDRAIN);
	registerEnum(interface, COMBAT_MANADRAIN);
	registerEnum(interface, COMBAT_HEALING);
	registerEnum(interface, COMBAT_DROWNDAMAGE);
	registerEnum(interface, COMBAT_ICEDAMAGE);
	registerEnum(interface, COMBAT_HOLYDAMAGE);
	registerEnum(interface, COMBAT_DEATHDAMAGE);

	registerEnum(interface, COMBAT_PARAM_TYPE);
	registerEnum(interface, COMBAT_PARAM_EFFECT);
	registerEnum(interface, COMBAT_PARAM_DISTANCEEFFECT);
	registerEnum(interface, COMBAT_PARAM_BLOCKSHIELD);
	registerEnum(interface, COMBAT_PARAM_BLOCKARMOR);
	registerEnum(interface, COMBAT_PARAM_TARGETCASTERORTOPMOST);
	registerEnum(interface, COMBAT_PARAM_CREATEITEM);
	registerEnum(interface, COMBAT_PARAM_AGGRESSIVE);
	registerEnum(interface, COMBAT_PARAM_DISPEL);
	registerEnum(interface, COMBAT_PARAM_USECHARGES);

	registerEnum(interface, CONDITION_NONE);
	registerEnum(interface, CONDITION_POISON);
	registerEnum(interface, CONDITION_FIRE);
	registerEnum(interface, CONDITION_ENERGY);
	registerEnum(interface, CONDITION_BLEEDING);
	registerEnum(interface, CONDITION_HASTE);
	registerEnum(interface, CONDITION_PARALYZE);
	registerEnum(interface, CONDITION_OUTFIT);
	registerEnum(interface, CONDITION_INVISIBLE);
	registerEnum(interface, CONDITION_LIGHT);
	registerEnum(interface, CONDITION_MANASHIELD);
	registerEnum(interface, CONDITION_INFIGHT);
	registerEnum(interface, CONDITION_DRUNK);
	registerEnum(interface, CONDITION_EXHAUST_WEAPON);
	registerEnum(interface, CONDITION_REGENERATION);
	registerEnum(interface, CONDITION_SOUL);
	registerEnum(interface, CONDITION_DROWN);
	registerEnum(interface, CONDITION_MUTED);
	registerEnum(interface, CONDITION_CHANNELMUTEDTICKS);
	registerEnum(interface, CONDITION_YELLTICKS);
	registerEnum(interface, CONDITION_ATTRIBUTES);
	registerEnum(interface, CONDITION_FREEZING);
	registerEnum(interface, CONDITION_DAZZLED);
	registerEnum(interface, CONDITION_CURSED);
	registerEnum(interface, CONDITION_EXHAUST_COMBAT);
	registerEnum(interface, CONDITION_EXHAUST_HEAL);
	registerEnum(interface, CONDITION_PACIFIED);
	registerEnum(interface, CONDITION_SPELLCOOLDOWN);
	registerEnum(interface, CONDITION_SPELLGROUPCOOLDOWN);
	registerEnum(interface, CONDITION_ROOT);

	registerEnum(interface, CONDITIONID_DEFAULT);
	registerEnum(interface, CONDITIONID_COMBAT);
	registerEnum(interface, CONDITIONID_HEAD);
	registerEnum(interface, CONDITIONID_NECKLACE);
	registerEnum(interface, CONDITIONID_BACKPACK);
	registerEnum(interface, CONDITIONID_ARMOR);
	registerEnum(interface, CONDITIONID_RIGHT);
	registerEnum(interface, CONDITIONID_LEFT);
	registerEnum(interface, CONDITIONID_LEGS);
	registerEnum(interface, CONDITIONID_FEET);
	registerEnum(interface, CONDITIONID_RING);
	registerEnum(interface, CONDITIONID_AMMO);

	registerEnum(interface, CONDITION_PARAM_OWNER);
	registerEnum(interface, CONDITION_PARAM_TICKS);
	registerEnum(interface, CONDITION_PARAM_DRUNKENNESS);
	registerEnum(interface, CONDITION_PARAM_HEALTHGAIN);
	registerEnum(interface, CONDITION_PARAM_HEALTHTICKS);
	registerEnum(interface, CONDITION_PARAM_MANAGAIN);
	registerEnum(interface, CONDITION_PARAM_MANATICKS);
	registerEnum(interface, CONDITION_PARAM_DELAYED);
	registerEnum(interface, CONDITION_PARAM_SPEED);
	registerEnum(interface, CONDITION_PARAM_LIGHT_LEVEL);
	registerEnum(interface, CONDITION_PARAM_LIGHT_COLOR);
	registerEnum(interface, CONDITION_PARAM_SOULGAIN);
	registerEnum(interface, CONDITION_PARAM_SOULTICKS);
	registerEnum(interface, CONDITION_PARAM_MINVALUE);
	registerEnum(interface, CONDITION_PARAM_MAXVALUE);
	registerEnum(interface, CONDITION_PARAM_STARTVALUE);
	registerEnum(interface, CONDITION_PARAM_TICKINTERVAL);
	registerEnum(interface, CONDITION_PARAM_FORCEUPDATE);
	registerEnum(interface, CONDITION_PARAM_SKILL_MELEE);
	registerEnum(interface, CONDITION_PARAM_SKILL_FIST);
	registerEnum(interface, CONDITION_PARAM_SKILL_CLUB);
	registerEnum(interface, CONDITION_PARAM_SKILL_SWORD);
	registerEnum(interface, CONDITION_PARAM_SKILL_AXE);
	registerEnum(interface, CONDITION_PARAM_SKILL_DISTANCE);
	registerEnum(interface, CONDITION_PARAM_SKILL_SHIELD);
	registerEnum(interface, CONDITION_PARAM_SKILL_FISHING);
	registerEnum(interface, CONDITION_PARAM_STAT_MAXHITPOINTS);
	registerEnum(interface, CONDITION_PARAM_STAT_MAXMANAPOINTS);
	registerEnum(interface, CONDITION_PARAM_STAT_MAGICPOINTS);
	registerEnum(interface, CONDITION_PARAM_STAT_MAXHITPOINTSPERCENT);
	registerEnum(interface, CONDITION_PARAM_STAT_MAXMANAPOINTSPERCENT);
	registerEnum(interface, CONDITION_PARAM_STAT_MAGICPOINTSPERCENT);
	registerEnum(interface, CONDITION_PARAM_PERIODICDAMAGE);
	registerEnum(interface, CONDITION_PARAM_SKILL_MELEEPERCENT);
	registerEnum(interface, CONDITION_PARAM_SKILL_FISTPERCENT);
	registerEnum(interface, CONDITION_PARAM_SKILL_CLUBPERCENT);
	registerEnum(interface, CONDITION_PARAM_SKILL_SWORDPERCENT);
	registerEnum(interface, CONDITION_PARAM_SKILL_AXEPERCENT);
	registerEnum(interface, CONDITION_PARAM_SKILL_DISTANCEPERCENT);
	registerEnum(interface, CONDITION_PARAM_SKILL_SHIELDPERCENT);
	registerEnum(interface, CONDITION_PARAM_SKILL_FISHINGPERCENT);
	registerEnum(interface, CONDITION_PARAM_BUFF_SPELL);
	registerEnum(interface, CONDITION_PARAM_SUBID);
	registerEnum(interface, CONDITION_PARAM_FIELD);
	registerEnum(interface, CONDITION_PARAM_DISABLE_DEFENSE);
	registerEnum(interface, CONDITION_PARAM_SPECIALSKILL_CRITICALHITCHANCE);
	registerEnum(interface, CONDITION_PARAM_SPECIALSKILL_CRITICALHITAMOUNT);
	registerEnum(interface, CONDITION_PARAM_SPECIALSKILL_LIFELEECHCHANCE);
	registerEnum(interface, CONDITION_PARAM_SPECIALSKILL_LIFELEECHAMOUNT);
	registerEnum(interface, CONDITION_PARAM_SPECIALSKILL_MANALEECHCHANCE);
	registerEnum(interface, CONDITION_PARAM_SPECIALSKILL_MANALEECHAMOUNT);
	registerEnum(interface, CONDITION_PARAM_AGGRESSIVE);

	registerEnum(interface, CONST_ME_NONE);
	registerEnum(interface, CONST_ME_DRAWBLOOD);
	registerEnum(interface, CONST_ME_LOSEENERGY);
	registerEnum(interface, CONST_ME_POFF);
	registerEnum(interface, CONST_ME_BLOCKHIT);
	registerEnum(interface, CONST_ME_EXPLOSIONAREA);
	registerEnum(interface, CONST_ME_EXPLOSIONHIT);
	registerEnum(interface, CONST_ME_FIREAREA);
	registerEnum(interface, CONST_ME_YELLOW_RINGS);
	registerEnum(interface, CONST_ME_GREEN_RINGS);
	registerEnum(interface, CONST_ME_HITAREA);
	registerEnum(interface, CONST_ME_TELEPORT);
	registerEnum(interface, CONST_ME_ENERGYHIT);
	registerEnum(interface, CONST_ME_MAGIC_BLUE);
	registerEnum(interface, CONST_ME_MAGIC_RED);
	registerEnum(interface, CONST_ME_MAGIC_GREEN);
	registerEnum(interface, CONST_ME_HITBYFIRE);
	registerEnum(interface, CONST_ME_HITBYPOISON);
	registerEnum(interface, CONST_ME_MORTAREA);
	registerEnum(interface, CONST_ME_SOUND_GREEN);
	registerEnum(interface, CONST_ME_SOUND_RED);
	registerEnum(interface, CONST_ME_POISONAREA);
	registerEnum(interface, CONST_ME_SOUND_YELLOW);
	registerEnum(interface, CONST_ME_SOUND_PURPLE);
	registerEnum(interface, CONST_ME_SOUND_BLUE);
	registerEnum(interface, CONST_ME_SOUND_WHITE);
	registerEnum(interface, CONST_ME_BUBBLES);
	registerEnum(interface, CONST_ME_CRAPS);
	registerEnum(interface, CONST_ME_GIFT_WRAPS);
	registerEnum(interface, CONST_ME_FIREWORK_YELLOW);
	registerEnum(interface, CONST_ME_FIREWORK_RED);
	registerEnum(interface, CONST_ME_FIREWORK_BLUE);
	registerEnum(interface, CONST_ME_STUN);
	registerEnum(interface, CONST_ME_SLEEP);
	registerEnum(interface, CONST_ME_WATERCREATURE);
	registerEnum(interface, CONST_ME_GROUNDSHAKER);
	registerEnum(interface, CONST_ME_HEARTS);
	registerEnum(interface, CONST_ME_FIREATTACK);
	registerEnum(interface, CONST_ME_ENERGYAREA);
	registerEnum(interface, CONST_ME_SMALLCLOUDS);
	registerEnum(interface, CONST_ME_HOLYDAMAGE);
	registerEnum(interface, CONST_ME_BIGCLOUDS);
	registerEnum(interface, CONST_ME_ICEAREA);
	registerEnum(interface, CONST_ME_ICETORNADO);
	registerEnum(interface, CONST_ME_ICEATTACK);
	registerEnum(interface, CONST_ME_STONES);
	registerEnum(interface, CONST_ME_SMALLPLANTS);
	registerEnum(interface, CONST_ME_CARNIPHILA);
	registerEnum(interface, CONST_ME_PURPLEENERGY);
	registerEnum(interface, CONST_ME_YELLOWENERGY);
	registerEnum(interface, CONST_ME_HOLYAREA);
	registerEnum(interface, CONST_ME_BIGPLANTS);
	registerEnum(interface, CONST_ME_CAKE);
	registerEnum(interface, CONST_ME_GIANTICE);
	registerEnum(interface, CONST_ME_WATERSPLASH);
	registerEnum(interface, CONST_ME_PLANTATTACK);
	registerEnum(interface, CONST_ME_TUTORIALARROW);
	registerEnum(interface, CONST_ME_TUTORIALSQUARE);
	registerEnum(interface, CONST_ME_MIRRORHORIZONTAL);
	registerEnum(interface, CONST_ME_MIRRORVERTICAL);
	registerEnum(interface, CONST_ME_SKULLHORIZONTAL);
	registerEnum(interface, CONST_ME_SKULLVERTICAL);
	registerEnum(interface, CONST_ME_ASSASSIN);
	registerEnum(interface, CONST_ME_STEPSHORIZONTAL);
	registerEnum(interface, CONST_ME_BLOODYSTEPS);
	registerEnum(interface, CONST_ME_STEPSVERTICAL);
	registerEnum(interface, CONST_ME_YALAHARIGHOST);
	registerEnum(interface, CONST_ME_BATS);
	registerEnum(interface, CONST_ME_SMOKE);
	registerEnum(interface, CONST_ME_INSECTS);
	registerEnum(interface, CONST_ME_DRAGONHEAD);
	registerEnum(interface, CONST_ME_ORCSHAMAN);
	registerEnum(interface, CONST_ME_ORCSHAMAN_FIRE);
	registerEnum(interface, CONST_ME_THUNDER);
	registerEnum(interface, CONST_ME_FERUMBRAS);
	registerEnum(interface, CONST_ME_CONFETTI_HORIZONTAL);
	registerEnum(interface, CONST_ME_CONFETTI_VERTICAL);
	registerEnum(interface, CONST_ME_BLACKSMOKE);
	registerEnum(interface, CONST_ME_REDSMOKE);
	registerEnum(interface, CONST_ME_YELLOWSMOKE);
	registerEnum(interface, CONST_ME_GREENSMOKE);
	registerEnum(interface, CONST_ME_PURPLESMOKE);
	registerEnum(interface, CONST_ME_EARLY_THUNDER);
	registerEnum(interface, CONST_ME_RAGIAZ_BONECAPSULE);
	registerEnum(interface, CONST_ME_CRITICAL_DAMAGE);
	registerEnum(interface, CONST_ME_PLUNGING_FISH);
	registerEnum(interface, CONST_ME_BLUECHAIN);
	registerEnum(interface, CONST_ME_ORANGECHAIN);
	registerEnum(interface, CONST_ME_GREENCHAIN);
	registerEnum(interface, CONST_ME_PURPLECHAIN);
	registerEnum(interface, CONST_ME_GREYCHAIN);
	registerEnum(interface, CONST_ME_YELLOWCHAIN);
	registerEnum(interface, CONST_ME_YELLOWSPARKLES);
	registerEnum(interface, CONST_ME_FAEEXPLOSION);
	registerEnum(interface, CONST_ME_FAECOMING);
	registerEnum(interface, CONST_ME_FAEGOING);
	registerEnum(interface, CONST_ME_BIGCLOUDSSINGLESPACE);
	registerEnum(interface, CONST_ME_STONESSINGLESPACE);
	registerEnum(interface, CONST_ME_BLUEGHOST);
	registerEnum(interface, CONST_ME_POINTOFINTEREST);
	registerEnum(interface, CONST_ME_MAPEFFECT);
	registerEnum(interface, CONST_ME_PINKSPARK);
	registerEnum(interface, CONST_ME_FIREWORK_GREEN);
	registerEnum(interface, CONST_ME_FIREWORK_ORANGE);
	registerEnum(interface, CONST_ME_FIREWORK_PURPLE);
	registerEnum(interface, CONST_ME_FIREWORK_TURQUOISE);
	registerEnum(interface, CONST_ME_THECUBE);
	registerEnum(interface, CONST_ME_DRAWINK);
	registerEnum(interface, CONST_ME_PRISMATICSPARKLES);
	registerEnum(interface, CONST_ME_THAIAN);
	registerEnum(interface, CONST_ME_THAIANGHOST);
	registerEnum(interface, CONST_ME_GHOSTSMOKE);
	registerEnum(interface, CONST_ME_FLOATINGBLOCK);
	registerEnum(interface, CONST_ME_BLOCK);
	registerEnum(interface, CONST_ME_ROOTING);
	registerEnum(interface, CONST_ME_GHOSTLYSCRATCH);
	registerEnum(interface, CONST_ME_GHOSTLYBITE);
	registerEnum(interface, CONST_ME_BIGSCRATCHING);
	registerEnum(interface, CONST_ME_SLASH);
	registerEnum(interface, CONST_ME_BITE);
	registerEnum(interface, CONST_ME_CHIVALRIOUSCHALLENGE);
	registerEnum(interface, CONST_ME_DIVINEDAZZLE);
	registerEnum(interface, CONST_ME_ELECTRICALSPARK);
	registerEnum(interface, CONST_ME_PURPLETELEPORT);
	registerEnum(interface, CONST_ME_REDTELEPORT);
	registerEnum(interface, CONST_ME_ORANGETELEPORT);
	registerEnum(interface, CONST_ME_GREYTELEPORT);
	registerEnum(interface, CONST_ME_LIGHTBLUETELEPORT);
	registerEnum(interface, CONST_ME_FATAL);
	registerEnum(interface, CONST_ME_DODGE);
	registerEnum(interface, CONST_ME_HOURGLASS);
	registerEnum(interface, CONST_ME_FIREWORKSSTAR);
	registerEnum(interface, CONST_ME_FIREWORKSCIRCLE);
	registerEnum(interface, CONST_ME_FERUMBRAS_1);
	registerEnum(interface, CONST_ME_GAZHARAGOTH);
	registerEnum(interface, CONST_ME_MAD_MAGE);
	registerEnum(interface, CONST_ME_HORESTIS);
	registerEnum(interface, CONST_ME_DEVOVORGA);
	registerEnum(interface, CONST_ME_FERUMBRAS_2);

	registerEnum(interface, CONST_ANI_NONE);
	registerEnum(interface, CONST_ANI_SPEAR);
	registerEnum(interface, CONST_ANI_BOLT);
	registerEnum(interface, CONST_ANI_ARROW);
	registerEnum(interface, CONST_ANI_FIRE);
	registerEnum(interface, CONST_ANI_ENERGY);
	registerEnum(interface, CONST_ANI_POISONARROW);
	registerEnum(interface, CONST_ANI_BURSTARROW);
	registerEnum(interface, CONST_ANI_THROWINGSTAR);
	registerEnum(interface, CONST_ANI_THROWINGKNIFE);
	registerEnum(interface, CONST_ANI_SMALLSTONE);
	registerEnum(interface, CONST_ANI_DEATH);
	registerEnum(interface, CONST_ANI_LARGEROCK);
	registerEnum(interface, CONST_ANI_SNOWBALL);
	registerEnum(interface, CONST_ANI_POWERBOLT);
	registerEnum(interface, CONST_ANI_POISON);
	registerEnum(interface, CONST_ANI_INFERNALBOLT);
	registerEnum(interface, CONST_ANI_HUNTINGSPEAR);
	registerEnum(interface, CONST_ANI_ENCHANTEDSPEAR);
	registerEnum(interface, CONST_ANI_REDSTAR);
	registerEnum(interface, CONST_ANI_GREENSTAR);
	registerEnum(interface, CONST_ANI_ROYALSPEAR);
	registerEnum(interface, CONST_ANI_SNIPERARROW);
	registerEnum(interface, CONST_ANI_ONYXARROW);
	registerEnum(interface, CONST_ANI_PIERCINGBOLT);
	registerEnum(interface, CONST_ANI_WHIRLWINDSWORD);
	registerEnum(interface, CONST_ANI_WHIRLWINDAXE);
	registerEnum(interface, CONST_ANI_WHIRLWINDCLUB);
	registerEnum(interface, CONST_ANI_ETHEREALSPEAR);
	registerEnum(interface, CONST_ANI_ICE);
	registerEnum(interface, CONST_ANI_EARTH);
	registerEnum(interface, CONST_ANI_HOLY);
	registerEnum(interface, CONST_ANI_SUDDENDEATH);
	registerEnum(interface, CONST_ANI_FLASHARROW);
	registerEnum(interface, CONST_ANI_FLAMMINGARROW);
	registerEnum(interface, CONST_ANI_SHIVERARROW);
	registerEnum(interface, CONST_ANI_ENERGYBALL);
	registerEnum(interface, CONST_ANI_SMALLICE);
	registerEnum(interface, CONST_ANI_SMALLHOLY);
	registerEnum(interface, CONST_ANI_SMALLEARTH);
	registerEnum(interface, CONST_ANI_EARTHARROW);
	registerEnum(interface, CONST_ANI_EXPLOSION);
	registerEnum(interface, CONST_ANI_CAKE);
	registerEnum(interface, CONST_ANI_TARSALARROW);
	registerEnum(interface, CONST_ANI_VORTEXBOLT);
	registerEnum(interface, CONST_ANI_PRISMATICBOLT);
	registerEnum(interface, CONST_ANI_CRYSTALLINEARROW);
	registerEnum(interface, CONST_ANI_DRILLBOLT);
	registerEnum(interface, CONST_ANI_ENVENOMEDARROW);
	registerEnum(interface, CONST_ANI_GLOOTHSPEAR);
	registerEnum(interface, CONST_ANI_SIMPLEARROW);
	registerEnum(interface, CONST_ANI_LEAFSTAR);
	registerEnum(interface, CONST_ANI_DIAMONDARROW);
	registerEnum(interface, CONST_ANI_SPECTRALBOLT);
	registerEnum(interface, CONST_ANI_ROYALSTAR);
	registerEnum(interface, CONST_ANI_WEAPONTYPE);

	registerEnum(interface, CONST_PROP_BLOCKSOLID);
	registerEnum(interface, CONST_PROP_HASHEIGHT);
	registerEnum(interface, CONST_PROP_BLOCKPROJECTILE);
	registerEnum(interface, CONST_PROP_BLOCKPATH);
	registerEnum(interface, CONST_PROP_ISVERTICAL);
	registerEnum(interface, CONST_PROP_ISHORIZONTAL);
	registerEnum(interface, CONST_PROP_MOVEABLE);
	registerEnum(interface, CONST_PROP_IMMOVABLEBLOCKSOLID);
	registerEnum(interface, CONST_PROP_IMMOVABLEBLOCKPATH);
	registerEnum(interface, CONST_PROP_IMMOVABLENOFIELDBLOCKPATH);
	registerEnum(interface, CONST_PROP_NOFIELDBLOCKPATH);
	registerEnum(interface, CONST_PROP_SUPPORTHANGABLE);

	registerEnum(interface, CONST_SLOT_HEAD);
	registerEnum(interface, CONST_SLOT_NECKLACE);
	registerEnum(interface, CONST_SLOT_BACKPACK);
	registerEnum(interface, CONST_SLOT_ARMOR);
	registerEnum(interface, CONST_SLOT_RIGHT);
	registerEnum(interface, CONST_SLOT_LEFT);
	registerEnum(interface, CONST_SLOT_LEGS);
	registerEnum(interface, CONST_SLOT_FEET);
	registerEnum(interface, CONST_SLOT_RING);
	registerEnum(interface, CONST_SLOT_AMMO);

	registerEnum(interface, CREATURE_EVENT_NONE);
	registerEnum(interface, CREATURE_EVENT_LOGIN);
	registerEnum(interface, CREATURE_EVENT_LOGOUT);
	registerEnum(interface, CREATURE_EVENT_THINK);
	registerEnum(interface, CREATURE_EVENT_PREPAREDEATH);
	registerEnum(interface, CREATURE_EVENT_DEATH);
	registerEnum(interface, CREATURE_EVENT_KILL);
	registerEnum(interface, CREATURE_EVENT_ADVANCE);
	registerEnum(interface, CREATURE_EVENT_MODALWINDOW);
	registerEnum(interface, CREATURE_EVENT_TEXTEDIT);
	registerEnum(interface, CREATURE_EVENT_HEALTHCHANGE);
	registerEnum(interface, CREATURE_EVENT_MANACHANGE);
	registerEnum(interface, CREATURE_EVENT_EXTENDED_OPCODE);

	registerEnum(interface, CREATURE_ID_MIN);
	registerEnum(interface, CREATURE_ID_MAX);

	registerEnum(interface, GAME_STATE_STARTUP);
	registerEnum(interface, GAME_STATE_INIT);
	registerEnum(interface, GAME_STATE_NORMAL);
	registerEnum(interface, GAME_STATE_CLOSED);
	registerEnum(interface, GAME_STATE_SHUTDOWN);
	registerEnum(interface, GAME_STATE_CLOSING);
	registerEnum(interface, GAME_STATE_MAINTAIN);

	registerEnum(interface, MESSAGE_STATUS_DEFAULT);
	registerEnum(interface, MESSAGE_STATUS_WARNING);
	registerEnum(interface, MESSAGE_EVENT_ADVANCE);
	registerEnum(interface, MESSAGE_STATUS_WARNING2);
	registerEnum(interface, MESSAGE_STATUS_SMALL);
	registerEnum(interface, MESSAGE_INFO_DESCR);
	registerEnum(interface, MESSAGE_DAMAGE_DEALT);
	registerEnum(interface, MESSAGE_DAMAGE_RECEIVED);
	registerEnum(interface, MESSAGE_HEALED);
	registerEnum(interface, MESSAGE_EXPERIENCE);
	registerEnum(interface, MESSAGE_DAMAGE_OTHERS);
	registerEnum(interface, MESSAGE_HEALED_OTHERS);
	registerEnum(interface, MESSAGE_EXPERIENCE_OTHERS);
	registerEnum(interface, MESSAGE_EVENT_DEFAULT);
	registerEnum(interface, MESSAGE_LOOT);
	registerEnum(interface, MESSAGE_TRADE);
	registerEnum(interface, MESSAGE_GUILD);
	registerEnum(interface, MESSAGE_PARTY_MANAGEMENT);
	registerEnum(interface, MESSAGE_PARTY);
	registerEnum(interface, MESSAGE_REPORT);
	registerEnum(interface, MESSAGE_HOTKEY_PRESSED);
	registerEnum(interface, MESSAGE_MARKET);
	registerEnum(interface, MESSAGE_BEYOND_LAST);
	registerEnum(interface, MESSAGE_TOURNAMENT_INFO);
	registerEnum(interface, MESSAGE_ATTENTION);
	registerEnum(interface, MESSAGE_BOOSTED_CREATURE);
	registerEnum(interface, MESSAGE_OFFLINE_TRAINING);
	registerEnum(interface, MESSAGE_TRANSACTION);

	registerEnum(interface, CREATURETYPE_PLAYER);
	registerEnum(interface, CREATURETYPE_MONSTER);
	registerEnum(interface, CREATURETYPE_NPC);
	registerEnum(interface, CREATURETYPE_SUMMON_OWN);
	registerEnum(interface, CREATURETYPE_SUMMON_OTHERS);

	registerEnum(interface, CLIENTOS_LINUX);
	registerEnum(interface, CLIENTOS_WINDOWS);
	registerEnum(interface, CLIENTOS_FLASH);
	registerEnum(interface, CLIENTOS_OTCLIENT_LINUX);
	registerEnum(interface, CLIENTOS_OTCLIENT_WINDOWS);
	registerEnum(interface, CLIENTOS_OTCLIENT_MAC);

	registerEnum(interface, FIGHTMODE_ATTACK);
	registerEnum(interface, FIGHTMODE_BALANCED);
	registerEnum(interface, FIGHTMODE_DEFENSE);

	registerEnum(interface, ITEM_ATTRIBUTE_NONE);
	registerEnum(interface, ITEM_ATTRIBUTE_ACTIONID);
	registerEnum(interface, ITEM_ATTRIBUTE_UNIQUEID);
	registerEnum(interface, ITEM_ATTRIBUTE_DESCRIPTION);
	registerEnum(interface, ITEM_ATTRIBUTE_TEXT);
	registerEnum(interface, ITEM_ATTRIBUTE_DATE);
	registerEnum(interface, ITEM_ATTRIBUTE_WRITER);
	registerEnum(interface, ITEM_ATTRIBUTE_NAME);
	registerEnum(interface, ITEM_ATTRIBUTE_ARTICLE);
	registerEnum(interface, ITEM_ATTRIBUTE_PLURALNAME);
	registerEnum(interface, ITEM_ATTRIBUTE_WEIGHT);
	registerEnum(interface, ITEM_ATTRIBUTE_ATTACK);
	registerEnum(interface, ITEM_ATTRIBUTE_DEFENSE);
	registerEnum(interface, ITEM_ATTRIBUTE_EXTRADEFENSE);
	registerEnum(interface, ITEM_ATTRIBUTE_ARMOR);
	registerEnum(interface, ITEM_ATTRIBUTE_HITCHANCE);
	registerEnum(interface, ITEM_ATTRIBUTE_SHOOTRANGE);
	registerEnum(interface, ITEM_ATTRIBUTE_OWNER);
	registerEnum(interface, ITEM_ATTRIBUTE_DURATION);
	registerEnum(interface, ITEM_ATTRIBUTE_DECAYSTATE);
	registerEnum(interface, ITEM_ATTRIBUTE_CORPSEOWNER);
	registerEnum(interface, ITEM_ATTRIBUTE_CHARGES);
	registerEnum(interface, ITEM_ATTRIBUTE_FLUIDTYPE);
	registerEnum(interface, ITEM_ATTRIBUTE_DOORID);
	registerEnum(interface, ITEM_ATTRIBUTE_DECAYTO);
	registerEnum(interface, ITEM_ATTRIBUTE_WRAPID);
	registerEnum(interface, ITEM_ATTRIBUTE_STOREITEM);
	registerEnum(interface, ITEM_ATTRIBUTE_ATTACK_SPEED);
	registerEnum(interface, ITEM_ATTRIBUTE_OPENCONTAINER);

	registerEnum(interface, ITEM_TYPE_DEPOT);
	registerEnum(interface, ITEM_TYPE_MAILBOX);
	registerEnum(interface, ITEM_TYPE_TRASHHOLDER);
	registerEnum(interface, ITEM_TYPE_CONTAINER);
	registerEnum(interface, ITEM_TYPE_DOOR);
	registerEnum(interface, ITEM_TYPE_MAGICFIELD);
	registerEnum(interface, ITEM_TYPE_TELEPORT);
	registerEnum(interface, ITEM_TYPE_BED);
	registerEnum(interface, ITEM_TYPE_KEY);
	registerEnum(interface, ITEM_TYPE_RUNE);
	registerEnum(interface, ITEM_TYPE_PODIUM);

	registerEnum(interface, ITEM_GROUP_GROUND);
	registerEnum(interface, ITEM_GROUP_CONTAINER);
	registerEnum(interface, ITEM_GROUP_WEAPON);
	registerEnum(interface, ITEM_GROUP_AMMUNITION);
	registerEnum(interface, ITEM_GROUP_ARMOR);
	registerEnum(interface, ITEM_GROUP_CHARGES);
	registerEnum(interface, ITEM_GROUP_TELEPORT);
	registerEnum(interface, ITEM_GROUP_MAGICFIELD);
	registerEnum(interface, ITEM_GROUP_WRITEABLE);
	registerEnum(interface, ITEM_GROUP_KEY);
	registerEnum(interface, ITEM_GROUP_SPLASH);
	registerEnum(interface, ITEM_GROUP_FLUID);
	registerEnum(interface, ITEM_GROUP_DOOR);
	registerEnum(interface, ITEM_GROUP_DEPRECATED);
	registerEnum(interface, ITEM_GROUP_PODIUM);

	registerEnum(interface, ITEM_BROWSEFIELD);
	registerEnum(interface, ITEM_BAG);
	registerEnum(interface, ITEM_SHOPPING_BAG);
	registerEnum(interface, ITEM_GOLD_COIN);
	registerEnum(interface, ITEM_PLATINUM_COIN);
	registerEnum(interface, ITEM_CRYSTAL_COIN);
	registerEnum(interface, ITEM_AMULETOFLOSS);
	registerEnum(interface, ITEM_PARCEL);
	registerEnum(interface, ITEM_LABEL);
	registerEnum(interface, ITEM_FIREFIELD_PVP_FULL);
	registerEnum(interface, ITEM_FIREFIELD_PVP_MEDIUM);
	registerEnum(interface, ITEM_FIREFIELD_PVP_SMALL);
	registerEnum(interface, ITEM_FIREFIELD_PERSISTENT_FULL);
	registerEnum(interface, ITEM_FIREFIELD_PERSISTENT_MEDIUM);
	registerEnum(interface, ITEM_FIREFIELD_PERSISTENT_SMALL);
	registerEnum(interface, ITEM_FIREFIELD_NOPVP);
	registerEnum(interface, ITEM_POISONFIELD_PVP);
	registerEnum(interface, ITEM_POISONFIELD_PERSISTENT);
	registerEnum(interface, ITEM_POISONFIELD_NOPVP);
	registerEnum(interface, ITEM_ENERGYFIELD_PVP);
	registerEnum(interface, ITEM_ENERGYFIELD_PERSISTENT);
	registerEnum(interface, ITEM_ENERGYFIELD_NOPVP);
	registerEnum(interface, ITEM_MAGICWALL);
	registerEnum(interface, ITEM_MAGICWALL_PERSISTENT);
	registerEnum(interface, ITEM_MAGICWALL_SAFE);
	registerEnum(interface, ITEM_WILDGROWTH);
	registerEnum(interface, ITEM_WILDGROWTH_PERSISTENT);
	registerEnum(interface, ITEM_WILDGROWTH_SAFE);
	registerEnum(interface, ITEM_DECORATION_KIT);

	registerEnum(interface, WIELDINFO_NONE);
	registerEnum(interface, WIELDINFO_LEVEL);
	registerEnum(interface, WIELDINFO_MAGLV);
	registerEnum(interface, WIELDINFO_VOCREQ);
	registerEnum(interface, WIELDINFO_PREMIUM);

	registerEnum(interface, PlayerFlag_CannotUseCombat);
	registerEnum(interface, PlayerFlag_CannotAttackPlayer);
	registerEnum(interface, PlayerFlag_CannotAttackMonster);
	registerEnum(interface, PlayerFlag_CannotBeAttacked);
	registerEnum(interface, PlayerFlag_CanConvinceAll);
	registerEnum(interface, PlayerFlag_CanSummonAll);
	registerEnum(interface, PlayerFlag_CanIllusionAll);
	registerEnum(interface, PlayerFlag_CanSenseInvisibility);
	registerEnum(interface, PlayerFlag_IgnoredByMonsters);
	registerEnum(interface, PlayerFlag_NotGainInFight);
	registerEnum(interface, PlayerFlag_HasInfiniteMana);
	registerEnum(interface, PlayerFlag_HasInfiniteSoul);
	registerEnum(interface, PlayerFlag_HasNoExhaustion);
	registerEnum(interface, PlayerFlag_CannotUseSpells);
	registerEnum(interface, PlayerFlag_CannotPickupItem);
	registerEnum(interface, PlayerFlag_CanAlwaysLogin);
	registerEnum(interface, PlayerFlag_CanBroadcast);
	registerEnum(interface, PlayerFlag_CanEditHouses);
	registerEnum(interface, PlayerFlag_CannotBeBanned);
	registerEnum(interface, PlayerFlag_CannotBePushed);
	registerEnum(interface, PlayerFlag_HasInfiniteCapacity);
	registerEnum(interface, PlayerFlag_CanPushAllCreatures);
	registerEnum(interface, PlayerFlag_CanTalkRedPrivate);
	registerEnum(interface, PlayerFlag_CanTalkRedChannel);
	registerEnum(interface, PlayerFlag_TalkOrangeHelpChannel);
	registerEnum(interface, PlayerFlag_NotGainExperience);
	registerEnum(interface, PlayerFlag_NotGainMana);
	registerEnum(interface, PlayerFlag_NotGainHealth);
	registerEnum(interface, PlayerFlag_NotGainSkill);
	registerEnum(interface, PlayerFlag_SetMaxSpeed);
	registerEnum(interface, PlayerFlag_SpecialVIP);
	registerEnum(interface, PlayerFlag_NotGenerateLoot);
	registerEnum(interface, PlayerFlag_IgnoreProtectionZone);
	registerEnum(interface, PlayerFlag_IgnoreSpellCheck);
	registerEnum(interface, PlayerFlag_IgnoreWeaponCheck);
	registerEnum(interface, PlayerFlag_CannotBeMuted);
	registerEnum(interface, PlayerFlag_IsAlwaysPremium);
	registerEnum(interface, PlayerFlag_IgnoreYellCheck);
	registerEnum(interface, PlayerFlag_IgnoreSendPrivateCheck);

	registerEnum(interface, PODIUM_SHOW_PLATFORM);
	registerEnum(interface, PODIUM_SHOW_OUTFIT);
	registerEnum(interface, PODIUM_SHOW_MOUNT);

	registerEnum(interface, PLAYERSEX_FEMALE);
	registerEnum(interface, PLAYERSEX_MALE);

	registerEnum(interface, REPORT_REASON_NAMEINAPPROPRIATE);
	registerEnum(interface, REPORT_REASON_NAMEPOORFORMATTED);
	registerEnum(interface, REPORT_REASON_NAMEADVERTISING);
	registerEnum(interface, REPORT_REASON_NAMEUNFITTING);
	registerEnum(interface, REPORT_REASON_NAMERULEVIOLATION);
	registerEnum(interface, REPORT_REASON_INSULTINGSTATEMENT);
	registerEnum(interface, REPORT_REASON_SPAMMING);
	registerEnum(interface, REPORT_REASON_ADVERTISINGSTATEMENT);
	registerEnum(interface, REPORT_REASON_UNFITTINGSTATEMENT);
	registerEnum(interface, REPORT_REASON_LANGUAGESTATEMENT);
	registerEnum(interface, REPORT_REASON_DISCLOSURE);
	registerEnum(interface, REPORT_REASON_RULEVIOLATION);
	registerEnum(interface, REPORT_REASON_STATEMENT_BUGABUSE);
	registerEnum(interface, REPORT_REASON_UNOFFICIALSOFTWARE);
	registerEnum(interface, REPORT_REASON_PRETENDING);
	registerEnum(interface, REPORT_REASON_HARASSINGOWNERS);
	registerEnum(interface, REPORT_REASON_FALSEINFO);
	registerEnum(interface, REPORT_REASON_ACCOUNTSHARING);
	registerEnum(interface, REPORT_REASON_STEALINGDATA);
	registerEnum(interface, REPORT_REASON_SERVICEATTACKING);
	registerEnum(interface, REPORT_REASON_SERVICEAGREEMENT);

	registerEnum(interface, REPORT_TYPE_NAME);
	registerEnum(interface, REPORT_TYPE_STATEMENT);
	registerEnum(interface, REPORT_TYPE_BOT);

	registerEnum(interface, VOCATION_NONE);

	registerEnum(interface, SKILL_FIST);
	registerEnum(interface, SKILL_CLUB);
	registerEnum(interface, SKILL_SWORD);
	registerEnum(interface, SKILL_AXE);
	registerEnum(interface, SKILL_DISTANCE);
	registerEnum(interface, SKILL_SHIELD);
	registerEnum(interface, SKILL_FISHING);
	registerEnum(interface, SKILL_MAGLEVEL);
	registerEnum(interface, SKILL_LEVEL);

	registerEnum(interface, SPECIALSKILL_CRITICALHITCHANCE);
	registerEnum(interface, SPECIALSKILL_CRITICALHITAMOUNT);
	registerEnum(interface, SPECIALSKILL_LIFELEECHCHANCE);
	registerEnum(interface, SPECIALSKILL_LIFELEECHAMOUNT);
	registerEnum(interface, SPECIALSKILL_MANALEECHCHANCE);
	registerEnum(interface, SPECIALSKILL_MANALEECHAMOUNT);

	registerEnum(interface, STAT_MAXHITPOINTS);
	registerEnum(interface, STAT_MAXMANAPOINTS);
	registerEnum(interface, STAT_SOULPOINTS);
	registerEnum(interface, STAT_MAGICPOINTS);

	registerEnum(interface, SKULL_NONE);
	registerEnum(interface, SKULL_YELLOW);
	registerEnum(interface, SKULL_GREEN);
	registerEnum(interface, SKULL_WHITE);
	registerEnum(interface, SKULL_RED);
	registerEnum(interface, SKULL_BLACK);
	registerEnum(interface, SKULL_ORANGE);

	registerEnum(interface, FLUID_NONE);
	registerEnum(interface, FLUID_WATER);
	registerEnum(interface, FLUID_BLOOD);
	registerEnum(interface, FLUID_BEER);
	registerEnum(interface, FLUID_SLIME);
	registerEnum(interface, FLUID_LEMONADE);
	registerEnum(interface, FLUID_MILK);
	registerEnum(interface, FLUID_MANA);
	registerEnum(interface, FLUID_LIFE);
	registerEnum(interface, FLUID_OIL);
	registerEnum(interface, FLUID_URINE);
	registerEnum(interface, FLUID_COCONUTMILK);
	registerEnum(interface, FLUID_WINE);
	registerEnum(interface, FLUID_MUD);
	registerEnum(interface, FLUID_FRUITJUICE);
	registerEnum(interface, FLUID_LAVA);
	registerEnum(interface, FLUID_RUM);
	registerEnum(interface, FLUID_SWAMP);
	registerEnum(interface, FLUID_TEA);
	registerEnum(interface, FLUID_MEAD);

	registerEnum(interface, TALKTYPE_SAY);
	registerEnum(interface, TALKTYPE_WHISPER);
	registerEnum(interface, TALKTYPE_YELL);
	registerEnum(interface, TALKTYPE_PRIVATE_FROM);
	registerEnum(interface, TALKTYPE_PRIVATE_TO);
	registerEnum(interface, TALKTYPE_CHANNEL_Y);
	registerEnum(interface, TALKTYPE_CHANNEL_O);
	registerEnum(interface, TALKTYPE_SPELL);
	registerEnum(interface, TALKTYPE_PRIVATE_NP);
	registerEnum(interface, TALKTYPE_PRIVATE_NP_CONSOLE);
	registerEnum(interface, TALKTYPE_PRIVATE_PN);
	registerEnum(interface, TALKTYPE_BROADCAST);
	registerEnum(interface, TALKTYPE_CHANNEL_R1);
	registerEnum(interface, TALKTYPE_PRIVATE_RED_FROM);
	registerEnum(interface, TALKTYPE_PRIVATE_RED_TO);
	registerEnum(interface, TALKTYPE_MONSTER_SAY);
	registerEnum(interface, TALKTYPE_MONSTER_YELL);
	registerEnum(interface, TALKTYPE_POTION);

	registerEnum(interface, TEXTCOLOR_BLUE);
	registerEnum(interface, TEXTCOLOR_LIGHTGREEN);
	registerEnum(interface, TEXTCOLOR_LIGHTBLUE);
	registerEnum(interface, TEXTCOLOR_MAYABLUE);
	registerEnum(interface, TEXTCOLOR_DARKRED);
	registerEnum(interface, TEXTCOLOR_LIGHTGREY);
	registerEnum(interface, TEXTCOLOR_SKYBLUE);
	registerEnum(interface, TEXTCOLOR_PURPLE);
	registerEnum(interface, TEXTCOLOR_ELECTRICPURPLE);
	registerEnum(interface, TEXTCOLOR_RED);
	registerEnum(interface, TEXTCOLOR_PASTELRED);
	registerEnum(interface, TEXTCOLOR_ORANGE);
	registerEnum(interface, TEXTCOLOR_YELLOW);
	registerEnum(interface, TEXTCOLOR_WHITE_EXP);
	registerEnum(interface, TEXTCOLOR_NONE);

	registerEnum(interface, TILESTATE_NONE);
	registerEnum(interface, TILESTATE_PROTECTIONZONE);
	registerEnum(interface, TILESTATE_NOPVPZONE);
	registerEnum(interface, TILESTATE_NOLOGOUT);
	registerEnum(interface, TILESTATE_PVPZONE);
	registerEnum(interface, TILESTATE_FLOORCHANGE);
	registerEnum(interface, TILESTATE_FLOORCHANGE_DOWN);
	registerEnum(interface, TILESTATE_FLOORCHANGE_NORTH);
	registerEnum(interface, TILESTATE_FLOORCHANGE_SOUTH);
	registerEnum(interface, TILESTATE_FLOORCHANGE_EAST);
	registerEnum(interface, TILESTATE_FLOORCHANGE_WEST);
	registerEnum(interface, TILESTATE_TELEPORT);
	registerEnum(interface, TILESTATE_MAGICFIELD);
	registerEnum(interface, TILESTATE_MAILBOX);
	registerEnum(interface, TILESTATE_TRASHHOLDER);
	registerEnum(interface, TILESTATE_BED);
	registerEnum(interface, TILESTATE_DEPOT);
	registerEnum(interface, TILESTATE_BLOCKSOLID);
	registerEnum(interface, TILESTATE_BLOCKPATH);
	registerEnum(interface, TILESTATE_IMMOVABLEBLOCKSOLID);
	registerEnum(interface, TILESTATE_IMMOVABLEBLOCKPATH);
	registerEnum(interface, TILESTATE_IMMOVABLENOFIELDBLOCKPATH);
	registerEnum(interface, TILESTATE_NOFIELDBLOCKPATH);
	registerEnum(interface, TILESTATE_FLOORCHANGE_SOUTH_ALT);
	registerEnum(interface, TILESTATE_FLOORCHANGE_EAST_ALT);
	registerEnum(interface, TILESTATE_SUPPORTS_HANGABLE);

	registerEnum(interface, WEAPON_NONE);
	registerEnum(interface, WEAPON_SWORD);
	registerEnum(interface, WEAPON_CLUB);
	registerEnum(interface, WEAPON_AXE);
	registerEnum(interface, WEAPON_SHIELD);
	registerEnum(interface, WEAPON_DISTANCE);
	registerEnum(interface, WEAPON_WAND);
	registerEnum(interface, WEAPON_AMMO);
	registerEnum(interface, WEAPON_QUIVER);

	registerEnum(interface, WORLD_TYPE_NO_PVP);
	registerEnum(interface, WORLD_TYPE_PVP);
	registerEnum(interface, WORLD_TYPE_PVP_ENFORCED);

	// Use with container:addItem, container:addItemEx and possibly other functions.
	registerEnum(interface, FLAG_NOLIMIT);
	registerEnum(interface, FLAG_IGNOREBLOCKITEM);
	registerEnum(interface, FLAG_IGNOREBLOCKCREATURE);
	registerEnum(interface, FLAG_CHILDISOWNER);
	registerEnum(interface, FLAG_PATHFINDING);
	registerEnum(interface, FLAG_IGNOREFIELDDAMAGE);
	registerEnum(interface, FLAG_IGNORENOTMOVEABLE);
	registerEnum(interface, FLAG_IGNOREAUTOSTACK);

	// Use with itemType:getSlotPosition
	registerEnum(interface, SLOTP_WHEREEVER);
	registerEnum(interface, SLOTP_HEAD);
	registerEnum(interface, SLOTP_NECKLACE);
	registerEnum(interface, SLOTP_BACKPACK);
	registerEnum(interface, SLOTP_ARMOR);
	registerEnum(interface, SLOTP_RIGHT);
	registerEnum(interface, SLOTP_LEFT);
	registerEnum(interface, SLOTP_LEGS);
	registerEnum(interface, SLOTP_FEET);
	registerEnum(interface, SLOTP_RING);
	registerEnum(interface, SLOTP_AMMO);
	registerEnum(interface, SLOTP_DEPOT);
	registerEnum(interface, SLOTP_TWO_HAND);

	// Use with combat functions
	registerEnum(interface, ORIGIN_NONE);
	registerEnum(interface, ORIGIN_CONDITION);
	registerEnum(interface, ORIGIN_SPELL);
	registerEnum(interface, ORIGIN_MELEE);
	registerEnum(interface, ORIGIN_RANGED);
	registerEnum(interface, ORIGIN_WAND);

	// Use with house:getAccessList, house:setAccessList
	registerEnum(interface, GUEST_LIST);
	registerEnum(interface, SUBOWNER_LIST);

	// Use with npc:setSpeechBubble
	registerEnum(interface, SPEECHBUBBLE_NONE);
	registerEnum(interface, SPEECHBUBBLE_NORMAL);
	registerEnum(interface, SPEECHBUBBLE_TRADE);
	registerEnum(interface, SPEECHBUBBLE_QUEST);
	registerEnum(interface, SPEECHBUBBLE_COMPASS);
	registerEnum(interface, SPEECHBUBBLE_NORMAL2);
	registerEnum(interface, SPEECHBUBBLE_NORMAL3);
	registerEnum(interface, SPEECHBUBBLE_HIRELING);

	// Use with player:addMapMark
	registerEnum(interface, MAPMARK_TICK);
	registerEnum(interface, MAPMARK_QUESTION);
	registerEnum(interface, MAPMARK_EXCLAMATION);
	registerEnum(interface, MAPMARK_STAR);
	registerEnum(interface, MAPMARK_CROSS);
	registerEnum(interface, MAPMARK_TEMPLE);
	registerEnum(interface, MAPMARK_KISS);
	registerEnum(interface, MAPMARK_SHOVEL);
	registerEnum(interface, MAPMARK_SWORD);
	registerEnum(interface, MAPMARK_FLAG);
	registerEnum(interface, MAPMARK_LOCK);
	registerEnum(interface, MAPMARK_BAG);
	registerEnum(interface, MAPMARK_SKULL);
	registerEnum(interface, MAPMARK_DOLLAR);
	registerEnum(interface, MAPMARK_REDNORTH);
	registerEnum(interface, MAPMARK_REDSOUTH);
	registerEnum(interface, MAPMARK_REDEAST);
	registerEnum(interface, MAPMARK_REDWEST);
	registerEnum(interface, MAPMARK_GREENNORTH);
	registerEnum(interface, MAPMARK_GREENSOUTH);

	// Use with Game.getReturnMessage
	registerEnum(interface, RETURNVALUE_NOERROR);
	registerEnum(interface, RETURNVALUE_NOTPOSSIBLE);
	registerEnum(interface, RETURNVALUE_NOTENOUGHROOM);
	registerEnum(interface, RETURNVALUE_PLAYERISPZLOCKED);
	registerEnum(interface, RETURNVALUE_PLAYERISNOTINVITED);
	registerEnum(interface, RETURNVALUE_CANNOTTHROW);
	registerEnum(interface, RETURNVALUE_THEREISNOWAY);
	registerEnum(interface, RETURNVALUE_DESTINATIONOUTOFREACH);
	registerEnum(interface, RETURNVALUE_CREATUREBLOCK);
	registerEnum(interface, RETURNVALUE_NOTMOVEABLE);
	registerEnum(interface, RETURNVALUE_DROPTWOHANDEDITEM);
	registerEnum(interface, RETURNVALUE_BOTHHANDSNEEDTOBEFREE);
	registerEnum(interface, RETURNVALUE_CANONLYUSEONEWEAPON);
	registerEnum(interface, RETURNVALUE_NEEDEXCHANGE);
	registerEnum(interface, RETURNVALUE_CANNOTBEDRESSED);
	registerEnum(interface, RETURNVALUE_PUTTHISOBJECTINYOURHAND);
	registerEnum(interface, RETURNVALUE_PUTTHISOBJECTINBOTHHANDS);
	registerEnum(interface, RETURNVALUE_TOOFARAWAY);
	registerEnum(interface, RETURNVALUE_FIRSTGODOWNSTAIRS);
	registerEnum(interface, RETURNVALUE_FIRSTGOUPSTAIRS);
	registerEnum(interface, RETURNVALUE_CONTAINERNOTENOUGHROOM);
	registerEnum(interface, RETURNVALUE_NOTENOUGHCAPACITY);
	registerEnum(interface, RETURNVALUE_CANNOTPICKUP);
	registerEnum(interface, RETURNVALUE_THISISIMPOSSIBLE);
	registerEnum(interface, RETURNVALUE_DEPOTISFULL);
	registerEnum(interface, RETURNVALUE_CREATUREDOESNOTEXIST);
	registerEnum(interface, RETURNVALUE_CANNOTUSETHISOBJECT);
	registerEnum(interface, RETURNVALUE_PLAYERWITHTHISNAMEISNOTONLINE);
	registerEnum(interface, RETURNVALUE_NOTREQUIREDLEVELTOUSERUNE);
	registerEnum(interface, RETURNVALUE_YOUAREALREADYTRADING);
	registerEnum(interface, RETURNVALUE_THISPLAYERISALREADYTRADING);
	registerEnum(interface, RETURNVALUE_YOUMAYNOTLOGOUTDURINGAFIGHT);
	registerEnum(interface, RETURNVALUE_DIRECTPLAYERSHOOT);
	registerEnum(interface, RETURNVALUE_NOTENOUGHLEVEL);
	registerEnum(interface, RETURNVALUE_NOTENOUGHMAGICLEVEL);
	registerEnum(interface, RETURNVALUE_NOTENOUGHMANA);
	registerEnum(interface, RETURNVALUE_NOTENOUGHSOUL);
	registerEnum(interface, RETURNVALUE_YOUAREEXHAUSTED);
	registerEnum(interface, RETURNVALUE_YOUCANNOTUSEOBJECTSTHATFAST);
	registerEnum(interface, RETURNVALUE_PLAYERISNOTREACHABLE);
	registerEnum(interface, RETURNVALUE_CANONLYUSETHISRUNEONCREATURES);
	registerEnum(interface, RETURNVALUE_ACTIONNOTPERMITTEDINPROTECTIONZONE);
	registerEnum(interface, RETURNVALUE_YOUMAYNOTATTACKTHISPLAYER);
	registerEnum(interface, RETURNVALUE_YOUMAYNOTATTACKAPERSONINPROTECTIONZONE);
	registerEnum(interface, RETURNVALUE_YOUMAYNOTATTACKAPERSONWHILEINPROTECTIONZONE);
	registerEnum(interface, RETURNVALUE_YOUMAYNOTATTACKTHISCREATURE);
	registerEnum(interface, RETURNVALUE_YOUCANONLYUSEITONCREATURES);
	registerEnum(interface, RETURNVALUE_CREATUREISNOTREACHABLE);
	registerEnum(interface, RETURNVALUE_TURNSECUREMODETOATTACKUNMARKEDPLAYERS);
	registerEnum(interface, RETURNVALUE_YOUNEEDPREMIUMACCOUNT);
	registerEnum(interface, RETURNVALUE_YOUNEEDTOLEARNTHISSPELL);
	registerEnum(interface, RETURNVALUE_YOURVOCATIONCANNOTUSETHISSPELL);
	registerEnum(interface, RETURNVALUE_YOUNEEDAWEAPONTOUSETHISSPELL);
	registerEnum(interface, RETURNVALUE_PLAYERISPZLOCKEDLEAVEPVPZONE);
	registerEnum(interface, RETURNVALUE_PLAYERISPZLOCKEDENTERPVPZONE);
	registerEnum(interface, RETURNVALUE_ACTIONNOTPERMITTEDINANOPVPZONE);
	registerEnum(interface, RETURNVALUE_YOUCANNOTLOGOUTHERE);
	registerEnum(interface, RETURNVALUE_YOUNEEDAMAGICITEMTOCASTSPELL);
	registerEnum(interface, RETURNVALUE_NAMEISTOOAMBIGUOUS);
	registerEnum(interface, RETURNVALUE_CANONLYUSEONESHIELD);
	registerEnum(interface, RETURNVALUE_NOPARTYMEMBERSINRANGE);
	registerEnum(interface, RETURNVALUE_YOUARENOTTHEOWNER);
	registerEnum(interface, RETURNVALUE_TRADEPLAYERFARAWAY);
	registerEnum(interface, RETURNVALUE_YOUDONTOWNTHISHOUSE);
	registerEnum(interface, RETURNVALUE_TRADEPLAYERALREADYOWNSAHOUSE);
	registerEnum(interface, RETURNVALUE_TRADEPLAYERHIGHESTBIDDER);
	registerEnum(interface, RETURNVALUE_YOUCANNOTTRADETHISHOUSE);
	registerEnum(interface, RETURNVALUE_YOUDONTHAVEREQUIREDPROFESSION);
	registerEnum(interface, RETURNVALUE_YOUCANNOTUSETHISBED);

	registerEnum(interface, RELOAD_TYPE_ALL);
	registerEnum(interface, RELOAD_TYPE_ACTIONS);
	registerEnum(interface, RELOAD_TYPE_CHAT);
	registerEnum(interface, RELOAD_TYPE_CONFIG);
	registerEnum(interface, RELOAD_TYPE_CREATURESCRIPTS);
	registerEnum(interface, RELOAD_TYPE_EVENTS);
	registerEnum(interface, RELOAD_TYPE_GLOBAL);
	registerEnum(interface, RELOAD_TYPE_GLOBALEVENTS);
	registerEnum(interface, RELOAD_TYPE_ITEMS);
	registerEnum(interface, RELOAD_TYPE_MONSTERS);
	registerEnum(interface, RELOAD_TYPE_MOUNTS);
	registerEnum(interface, RELOAD_TYPE_MOVEMENTS);
	registerEnum(interface, RELOAD_TYPE_NPCS);
	registerEnum(interface, RELOAD_TYPE_QUESTS);
	registerEnum(interface, RELOAD_TYPE_RAIDS);
	registerEnum(interface, RELOAD_TYPE_SCRIPTS);
	registerEnum(interface, RELOAD_TYPE_SPELLS);
	registerEnum(interface, RELOAD_TYPE_TALKACTIONS);
	registerEnum(interface, RELOAD_TYPE_WEAPONS);

	registerEnum(interface, ZONE_PROTECTION);
	registerEnum(interface, ZONE_NOPVP);
	registerEnum(interface, ZONE_PVP);
	registerEnum(interface, ZONE_NOLOGOUT);
	registerEnum(interface, ZONE_NORMAL);

	registerEnum(interface, MAX_LOOTCHANCE);

	registerEnum(interface, SPELL_INSTANT);
	registerEnum(interface, SPELL_RUNE);

	registerEnum(interface, MONSTERS_EVENT_THINK);
	registerEnum(interface, MONSTERS_EVENT_APPEAR);
	registerEnum(interface, MONSTERS_EVENT_DISAPPEAR);
	registerEnum(interface, MONSTERS_EVENT_MOVE);
	registerEnum(interface, MONSTERS_EVENT_SAY);

	registerEnum(interface, DECAYING_FALSE);
	registerEnum(interface, DECAYING_TRUE);
	registerEnum(interface, DECAYING_PENDING);

	// configKeys
	interface->registerTable("configKeys");

	registerEnumIn(interface, "configKeys", ConfigManager::ALLOW_CHANGEOUTFIT);
	registerEnumIn(interface, "configKeys", ConfigManager::ONE_PLAYER_ON_ACCOUNT);
	registerEnumIn(interface, "configKeys", ConfigManager::AIMBOT_HOTKEY_ENABLED);
	registerEnumIn(interface, "configKeys", ConfigManager::REMOVE_RUNE_CHARGES);
	registerEnumIn(interface, "configKeys", ConfigManager::REMOVE_WEAPON_AMMO);
	registerEnumIn(interface, "configKeys", ConfigManager::REMOVE_WEAPON_CHARGES);
	registerEnumIn(interface, "configKeys", ConfigManager::REMOVE_POTION_CHARGES);
	registerEnumIn(interface, "configKeys", ConfigManager::EXPERIENCE_FROM_PLAYERS);
	registerEnumIn(interface, "configKeys", ConfigManager::FREE_PREMIUM);
	registerEnumIn(interface, "configKeys", ConfigManager::REPLACE_KICK_ON_LOGIN);
	registerEnumIn(interface, "configKeys", ConfigManager::ALLOW_CLONES);
	registerEnumIn(interface, "configKeys", ConfigManager::BIND_ONLY_GLOBAL_ADDRESS);
	registerEnumIn(interface, "configKeys", ConfigManager::OPTIMIZE_DATABASE);
	registerEnumIn(interface, "configKeys", ConfigManager::MARKET_PREMIUM);
	registerEnumIn(interface, "configKeys", ConfigManager::EMOTE_SPELLS);
	registerEnumIn(interface, "configKeys", ConfigManager::STAMINA_SYSTEM);
	registerEnumIn(interface, "configKeys", ConfigManager::WARN_UNSAFE_SCRIPTS);
	registerEnumIn(interface, "configKeys", ConfigManager::CONVERT_UNSAFE_SCRIPTS);
	registerEnumIn(interface, "configKeys", ConfigManager::CLASSIC_EQUIPMENT_SLOTS);
	registerEnumIn(interface, "configKeys", ConfigManager::CLASSIC_ATTACK_SPEED);
	registerEnumIn(interface, "configKeys", ConfigManager::SERVER_SAVE_NOTIFY_MESSAGE);
	registerEnumIn(interface, "configKeys", ConfigManager::SERVER_SAVE_NOTIFY_DURATION);
	registerEnumIn(interface, "configKeys", ConfigManager::SERVER_SAVE_CLEAN_MAP);
	registerEnumIn(interface, "configKeys", ConfigManager::SERVER_SAVE_CLOSE);
	registerEnumIn(interface, "configKeys", ConfigManager::SERVER_SAVE_SHUTDOWN);
	registerEnumIn(interface, "configKeys", ConfigManager::ONLINE_OFFLINE_CHARLIST);

	registerEnumIn(interface, "configKeys", ConfigManager::MAP_NAME);
	registerEnumIn(interface, "configKeys", ConfigManager::HOUSE_RENT_PERIOD);
	registerEnumIn(interface, "configKeys", ConfigManager::SERVER_NAME);
	registerEnumIn(interface, "configKeys", ConfigManager::OWNER_NAME);
	registerEnumIn(interface, "configKeys", ConfigManager::OWNER_EMAIL);
	registerEnumIn(interface, "configKeys", ConfigManager::URL);
	registerEnumIn(interface, "configKeys", ConfigManager::LOCATION);
	registerEnumIn(interface, "configKeys", ConfigManager::IP);
	registerEnumIn(interface, "configKeys", ConfigManager::WORLD_TYPE);
	registerEnumIn(interface, "configKeys", ConfigManager::MYSQL_HOST);
	registerEnumIn(interface, "configKeys", ConfigManager::MYSQL_USER);
	registerEnumIn(interface, "configKeys", ConfigManager::MYSQL_PASS);
	registerEnumIn(interface, "configKeys", ConfigManager::MYSQL_DB);
	registerEnumIn(interface, "configKeys", ConfigManager::MYSQL_SOCK);
	registerEnumIn(interface, "configKeys", ConfigManager::DEFAULT_PRIORITY);
	registerEnumIn(interface, "configKeys", ConfigManager::MAP_AUTHOR);

	registerEnumIn(interface, "configKeys", ConfigManager::SQL_PORT);
	registerEnumIn(interface, "configKeys", ConfigManager::MAX_PLAYERS);
	registerEnumIn(interface, "configKeys", ConfigManager::PZ_LOCKED);
	registerEnumIn(interface, "configKeys", ConfigManager::DEFAULT_DESPAWNRANGE);
	registerEnumIn(interface, "configKeys", ConfigManager::DEFAULT_DESPAWNRADIUS);
	registerEnumIn(interface, "configKeys", ConfigManager::DEFAULT_WALKTOSPAWNRADIUS);
	registerEnumIn(interface, "configKeys", ConfigManager::REMOVE_ON_DESPAWN);
	registerEnumIn(interface, "configKeys", ConfigManager::RATE_EXPERIENCE);
	registerEnumIn(interface, "configKeys", ConfigManager::RATE_SKILL);
	registerEnumIn(interface, "configKeys", ConfigManager::RATE_LOOT);
	registerEnumIn(interface, "configKeys", ConfigManager::RATE_MAGIC);
	registerEnumIn(interface, "configKeys", ConfigManager::RATE_SPAWN);
	registerEnumIn(interface, "configKeys", ConfigManager::HOUSE_PRICE);
	registerEnumIn(interface, "configKeys", ConfigManager::KILLS_TO_RED);
	registerEnumIn(interface, "configKeys", ConfigManager::KILLS_TO_BLACK);
	registerEnumIn(interface, "configKeys", ConfigManager::MAX_MESSAGEBUFFER);
	registerEnumIn(interface, "configKeys", ConfigManager::ACTIONS_DELAY_INTERVAL);
	registerEnumIn(interface, "configKeys", ConfigManager::EX_ACTIONS_DELAY_INTERVAL);
	registerEnumIn(interface, "configKeys", ConfigManager::KICK_AFTER_MINUTES);
	registerEnumIn(interface, "configKeys", ConfigManager::PROTECTION_LEVEL);
	registerEnumIn(interface, "configKeys", ConfigManager::DEATH_LOSE_PERCENT);
	registerEnumIn(interface, "configKeys", ConfigManager::STATUSQUERY_TIMEOUT);
	registerEnumIn(interface, "configKeys", ConfigManager::FRAG_TIME);
	registerEnumIn(interface, "configKeys", ConfigManager::WHITE_SKULL_TIME);
	registerEnumIn(interface, "configKeys", ConfigManager::GAME_PORT);
	registerEnumIn(interface, "configKeys", ConfigManager::LOGIN_PORT);
	registerEnumIn(interface, "configKeys", ConfigManager::STATUS_PORT);
	registerEnumIn(interface, "configKeys", ConfigManager::STAIRHOP_DELAY);
	registerEnumIn(interface, "configKeys", ConfigManager::MARKET_OFFER_DURATION);
	registerEnumIn(interface, "configKeys", ConfigManager::CHECK_EXPIRED_MARKET_OFFERS_EACH_MINUTES);
	registerEnumIn(interface, "configKeys", ConfigManager::MAX_MARKET_OFFERS_AT_A_TIME_PER_PLAYER);
	registerEnumIn(interface, "configKeys", ConfigManager::EXP_FROM_PLAYERS_LEVEL_RANGE);
	registerEnumIn(interface, "configKeys", ConfigManager::MAX_PACKETS_PER_SECOND);
	registerEnumIn(interface, "configKeys", ConfigManager::PLAYER_CONSOLE_LOGS);
	registerEnumIn(interface, "configKeys", ConfigManager::TWO_FACTOR_AUTH);
	registerEnumIn(interface, "configKeys", ConfigManager::STAMINA_REGEN_MINUTE);
	registerEnumIn(interface, "configKeys", ConfigManager::STAMINA_REGEN_PREMIUM);
}
